var urls=[
//zhongdou
"http://api.turinglabs.net/api/v1/jd/bean/create/khqmdowxkuwyd22kbhbbodm44u/",
"http://api.turinglabs.net/api/v1/jd/bean/create/e7lhibzb3zek3pmgxuv6hfasgturjncr4y3ca5a/",
"http://api.turinglabs.net/api/v1/jd/bean/create/o5fzrgfqcghdz6kgnjpafga3qemex4wi6rifvfi/",
"http://api.turinglabs.net/api/v1/jd/bean/create/u4hsumwvd5xczfreaprd465o3m/",
"http://api.turinglabs.net/api/v1/jd/bean/create/olmijoxgmjutzweslp4mbpwd2geg44d7lmg7pyq/",
"http://api.turinglabs.net/api/v1/jd/bean/create/azmdtikj6fisglhrbkxsjmgnxu/",
"http://api.turinglabs.net/api/v1/jd/bean/create/nled2ntrchuugtagqumsbywn5e/",
"http://api.turinglabs.net/api/v1/jd/bean/create/lhubofhlunfauokupvpj5liy3e/",
"http://api.turinglabs.net/api/v1/jd/bean/create/kohtucyu3skrn2pumlk24oc2le3h7wlwy7o5jii/",
"http://api.turinglabs.net/api/v1/jd/bean/create/olmijoxgmjutzkq5hz2yovht3dljeosj4ocl6li/",
"http://api.turinglabs.net/api/v1/jd/bean/create/epes65uva7oux4dlvgnottar7nxgb3lluyuhjta/",
"http://api.turinglabs.net/api/v1/jd/bean/create/e7lhibzb3zek34yactwe3maes7xxckhibgdn3ni/",
"http://api.turinglabs.net/api/v1/jd/bean/create/olmijoxgmjutze5pyafoogcob4jdhdic5numtpq/",
"http://api.turinglabs.net/api/v1/jd/bean/create/wkx54sxpzacxgq4gu6afvy6paq/",
"http://api.turinglabs.net/api/v1/jd/bean/create/caosyxxrxasx3elbrfdjcmuyr2fe2ocup5wbvpy/",
//nongchang
"http://api.turinglabs.net/api/v1/jd/farm/create/52eee5f1d9c7405d8df5c33a225312d6/",
"http://api.turinglabs.net/api/v1/jd/farm/create/a75e0a0dc575494ebdd12730caa7e423/",
"http://api.turinglabs.net/api/v1/jd/farm/create/879f1300f8c848d484189f277ffa4b42/",
"http://api.turinglabs.net/api/v1/jd/farm/create/53922e9d1d234261b805076bfe62eb7f/",
"http://api.turinglabs.net/api/v1/jd/farm/create/4da5aac9b6ca454a9b0ff79d7b87b8f4/",
"http://api.turinglabs.net/api/v1/jd/farm/create/1edb55fdd6ca46e3be6b61bd881679c0/",
"http://api.turinglabs.net/api/v1/jd/farm/create/498248e201ea425c8aa9bc9110c6d63f/",
"http://api.turinglabs.net/api/v1/jd/farm/create/0b1e78fd0cd64fa48c91b0c9122245ce/",
"http://api.turinglabs.net/api/v1/jd/farm/create/071757282d974feab0f30d2f3d9f6485/",
"http://api.turinglabs.net/api/v1/jd/farm/create/e1cebad56b0246c895521f23b45dfc37/",
"http://api.turinglabs.net/api/v1/jd/farm/create/52b1eb07f5e04c38b543d1c03207af35/",
"http://api.turinglabs.net/api/v1/jd/farm/create/4e8f5b9125b74a119f15d644db038663/",
"http://api.turinglabs.net/api/v1/jd/farm/create/a4be6a08f5c1492793d28a3f868bf6e8/",
"http://api.turinglabs.net/api/v1/jd/farm/create/748f3c6f77a5409297d6f6f33c607116/",
"http://api.turinglabs.net/api/v1/jd/farm/create/e88dc95dbdd84228b349e504c324d8e1/",
"http://api.turinglabs.net/api/v1/jd/farm/create/474682cd7d0e4c429c9d568acb973b64/",
"http://api.turinglabs.net/api/v1/jd/farm/create/b4ef5b59681446f58273d1643d9de55e/",
//mengchong
"http://api.turinglabs.net/api/v1/jd/pet/create/MTAxODcxOTI2NTAwMDAwMDAzMjQ4Mzc2NQ==/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTAxODc2NTEzMTAwMDAwMDAzMjQ1ODY4Mw==/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDAxNzYwMDAwMDAwMzU2MjUzMTk=/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDQ5OTUwMDAwMDAwMzg4MzgxMzk=/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTAxODc2NTEzMTAwMDAwMDAyNzA5ODkxMw==/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTAxODc2NTEzNTAwMDAwMDAzMzYxMjY1Nw==/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDUyMjEwMDAwMDAwNDAyMDY5NDc=/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDAxNzgwMDAwMDAwMzM4MDU1MTk=/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTAxODExNDYxMTEwMDAwMDAwNDA2ODY3MjM=/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDAxNzcwMDAwMDAwNDA4NDU3NTM=/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDUyMjEwMDAwMDAwNDIxMDE1OTk=/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDQ5OTUwMDAwMDAwNDI1NzMwMTM=/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDUwMTI0MDAwMDAwMDQyNTkyOTYx/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDQ5OTUwMDAwMDAwNDMwMDA3ODk=/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTAxODc2NTEzOTAwMDAwMDAyMTc2MzE4OQ==/",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDQ5MzYwMDAwMDAwNDMxMDIxNjk=",
"http://api.turinglabs.net/api/v1/jd/pet/create/MTE1NDUyMjEwMDAwMDAwNDMxMDU0ODU=/",
//dongdonggongchang
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5mlRWT6vlTkfz8btjoyLAHA/",
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5n9SWTmklzU/",
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5m9cZ2b62n1NlB-nRByxSCU/",             
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5nxNVzy6/",
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5jAMCmfx2HlInGJu/",
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5m9ZXD-miiATyw/",
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5m9cZ2Su2i8ekH69_oYpf0k/",
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5n1RWT-4jCIWwJo/",
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5jQAC2b9339MkP6uy1w/",
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5m9cZ2b6jnVOnNFaUshfAtk/",
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5jQPC2P63HRNiBRZYnwob0AM/",
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5m9cZ2Twi3tLkOF-AK3xXao/",
"http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5m9cZ2asjHkfw-KWBiglfnk/",
//jingxigongchang
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/kj1iZnvw5Cvhsr2GmJ13sw==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/mylLCjV__Rk9vW57GEmjyw==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/qTfgATX37pPF6NzMldVw1g==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/DZ06Bx-hxsCcVr3baxRGGw==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/Gv2RRMavf0BvXUgx2Llrpw==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/eoPOkdTrwwSLT-kS3cIdiw==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/uAwlAHK8ZwFAWILkcVy9dw==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/ySA8JN-ysAD7TL6KMFHPnQ==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/Tzg-BNrWIEzScY6mCgjk0w==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/VZChEycbyLXQJpgijbj32g==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/UG29wzmYwRHt-wAGfaOYVoZs-bk3MInqg5q8MhWU9s0=/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/InLoOkNv8X9IMz9s81vi1Q==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/mQxITCRFdU78wFCYqbZ5QA==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/nrYnepK45_13dCClag9zDg==/",
"http://api.turinglabs.net/api/v1/jd/jxfactory/create/6sUn5QR4gcDLKA7vs8E1CA==/",
//crazy_joy
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/WTg_NIsdTKtq12gDi5H5_qt9zd5YaBeE/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/mmzE89N1KAc=/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/ViB0BC9y0sNTpNSwa0GjP6t9zd5YaBeE/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/1YV9M3IsC68=/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/rbA0WZgcj5RwiiG3q0ckVw==/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/gS7V4zeTyRIO5qSJz0JnZw==/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/mKWs8ldCAcNzX2E1bFY50at9zd5YaBeE/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/B8z1fFiAvN3K-wu_K7T0OQ==/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/lQowGmJNf71mDNFfDrbNDQ==/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/4FzN_wNqZzQYNxwR0iEDuKt9zd5YaBeE/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/E1lBwlCF4x-4Ffhhl5R8QShrW-lv9zNY/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/1lEZKI9KcZoYR7fFbLOYMat9zd5YaBeE/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/EsXINYVaGg5wUiSKNKMFCKt9zd5YaBeE/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/ErCWih921XGrfc3eWGgXhA==/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/LOsN9U_STr-6PD-kNuyiYw==/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/CU-4XL55rg6No7tquxFmf6t9zd5YaBeE/"£¬
"https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/CNvu7MIGAgaAkR0ePKnc2at9zd5YaBeE/"£¬
//jd_zz  
"https://code.chiang.fun/api/v1/jd/jdzz/create/S4qQiHklRsAGNeUSjwKhUIw/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S9KciGUJTvA/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S5KkcRhwe9FPWdUymk6QKJQ/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S97gsHFw/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/Su_lxRxcc8FbeT0c/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S5KwnH0BOqQ2J/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S5KkcREgepgDSchv0nPAJdw/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S9qQiH15IqwiCeQ/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/Sv_VwRhsb9lLSIRib1A/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S5KkcRhxK_FDechqinP4IcA/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/Sv_pwQxwY_VPKJx70nfQDfM4/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S5KkcRBZP8lXSJR32kKENIg/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S5KkcRkpI8AGBdhynnfdedg/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S5qwnFV1FrAo/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/SZkbMl5WXIthG9Y5jQH2A/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S5KkcRxxMplbQKE6gwqJedg/"£¬
"https://code.chiang.fun/api/v1/jd/jdzz/create/S5KkcRR0eoQKEdR6glPJYdg/"£¬

]
urls.forEach(url => {
    $httpClient.get(url,function(error, response, data){
        console.log(response);
    });
});
